# Generated by Django 5.1.4 on 2025-03-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_businesssubject_favorite_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='webpush_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
