# Generated by Django 5.1.4 on 2025-06-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_client_age_client_gender_client_webpush_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='webpush_info',
        ),
    ]
