# Generated by Django 5.1.4 on 2025-06-18 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_client_webpush_info'),
        ('activities', '0013_activities_duration_hours_comment_and_more'),
        ('advertisements', '0010_advertisement_duration_hours'),
        ('notifications', '0002_alter_notification_notification_type'),
        ('push_notifications', '0012_alter_apnsdevice_id_alter_gcmdevice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('odjava', 'Odjava'), ('prijava', 'Prijava'), ('komentar', 'Komentar'), ('uskoro', 'Uskoro'), ('activity_delete', 'ACTIVITY_DELETE'), ('azuriranje', 'Update')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationGeneric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('odjava', 'Odjava'), ('prijava', 'Prijava'), ('komentar', 'Komentar'), ('uskoro', 'Uskoro'), ('activity_delete', 'ACTIVITY_DELETE'), ('azuriranje', 'Update'), ('system', 'SYSTEM')], max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_activity', to='activities.activities')),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_advertisement', to='advertisements.advertisement')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_comment', to='activities.comment')),
                ('recipient_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieve_notifications_client', to='accounts.client')),
                ('recipient_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieve_notifications_client', to='accounts.businesssubject')),
                ('sender_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications_client', to='accounts.client')),
                ('sender_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications_subject', to='accounts.businesssubject')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=False)),
                ('group_notifications', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_preference', to='accounts.client')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_preference', to='accounts.businesssubject')),
            ],
        ),
        migrations.CreateModel(
            name='WebPushInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='push_notifications.webpushdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.client')),
            ],
            options={
                'db_table': 'webpushinfo',
                'unique_together': {('user', 'device')},
            },
        ),
        migrations.CreateModel(
            name='WebPushInfoBusinessSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registration', to='push_notifications.webpushdevice')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_device', to='accounts.businesssubject')),
            ],
            options={
                'unique_together': {('subject', 'device')},
            },
        ),
    ]
