# Generated by Django 5.1.4 on 2025-03-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='chat', max_length=255),
            preserve_default=False,
        ),
    ]
