# Generated by Django 5.1.4 on 2025-06-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_deleted_message_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
